### ISSUE TITLE
Example of Elmah.ErrorMail.config?

### ISSUE THREAD

**Issue by weiminye** [elmah/Bootstrapper#12]
Everyone can provide an example of Elmah.ErrorMail.config? thanks in advance

**Comment by atifaziz** [comment]
Sure, the `Elmah.ErrorMail.config` is a basically section-less [INI file](https://en.wikipedia.org/wiki/INI_file) of key-value pairs as follows:

```ini
to=alice@example.com
cc=bob@example.com
bcc=charlie@example.com
```

Like in an INI file, a line can be commented out be starting with with a semi-colon (;):

```ini
to=alice@example.com
cc=bob@example.com
;bcc=charlie@example.com
```

You can also address multiple recipient by separating them with commas:

```
to=alice@example.com,john@example.com
cc=bob@example.com
bcc=charlie@example.com
```

Alternatively, you can also set the same key several times, like `to` in the example below, to address multiple recipients:

```
to=alice@example.com
to=john@example.com
cc=bob@example.com
bcc=charlie@example.com
```

The only supported configuration keys are `to`, `cc` and `bcc` as shown in all the examples above, and all of which are optional.

If this helped then please consider closing the issue.

**Comment by weiminye** [comment]
Thanks your reply.

so doesn't support configuration keys like :  `from`, `subject` , `async`, `smtpServer`, `userName`, `password`, `useSsl` ?

if doesn't support, does have other way to support?

**Comment by atifaziz** [comment]
> so doesn't support configuration keys like :  `from`, `subject` , `async`, `smtpServer`, `userName`, `password`, `useSsl` ?

No because that sort of configuration is not expected to change frequently whereas you might want to configure different recipients often without causing a restart of the application (as would be the case with configuration, like above, in `web.config`).

> if doesn't support, does have other way to support?

Yes! The [`ErrorMailModule` in ELMAH has supported firing events when emailing an error notification](http://scottonwriting.net/sowblog/archive/2011/01/06/customizing-elmah-s-error-emails.aspx). This project builds on that, makes it easier and even supports more customization.

You can subscribe to the mailing event like this:

```c#
App.OnModuleEvent(
    (m, h) => m.Mailing += h,
    (m, h) => m.Mailing -= h,
    h => new ErrorMailEventHandler((sender, args) => h(sender, args)),
    (Elmah.ErrorMailModule sender, ErrorMailEventArgs args) =>
    {
        // TODO event handling code
    });
```

This should happen during the start-up or initialization of your web application. Below is an example of a mailing event handler that sends the e-mail itself and then tells ELMAH to skip its own logic to send one (to avoid a duplicate) by setting `ShouldNotSend` to `true`:

```c#
App.OnModuleEvent(
    (m, h) => m.Mailing += h,
    (m, h) => m.Mailing -= h,
    h => new ErrorMailEventHandler((sender, args) => h(sender, args)),
    (Elmah.ErrorMailModule sender, ErrorMailEventArgs args) =>
    {
        var tag = args.Mail.GetTag();
        var config = tag.ErrorMailModuleSmtpConfiguration;
        var smtp = new SmtpClient(config.Host, config.Port);
        smtp.Send(args.Mail);
        tag.ShouldNotSend = true;
    });
```

You could code up your own logic to read configuration from anywhere.

---
If this helped then please consider closing the issue.

**Comment by sachinshrestha483** [comment]
`asdsds
dsds
dsds
d`
